# Generated by Django 5.0.2 on 2024-03-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rescipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rescipe_name', models.CharField(max_length=100)),
                ('rescipe_description', models.TextField()),
                ('rescipe_image', models.ImageField(upload_to='rescipe')),
            ],
        ),
    ]
